### ISSUE TITLE
Not able to load the GitHub son file into python with Json.loads()

### ISSUE THREAD

**Issue by mdedhe** [mdedhe/OpenSourcePaper#1]
I tried to load a  the downloaded file from the GitHub into Json to analyse the data on basis of key value pair but I got an error after dumping that into the Json. 
File wasn't a Json I need to create into Json that took lot of time

#Give the file Path
file=open('/Users/mohitdedhe/Desktop/MohitsDocs/Certification and Projects/VProject/Files/2015-01-07-11.json',encoding='utf-8')
#Read the contain of the file
data= file.read()
#dump the data into json
records=json.dumps(data)
#load the string data into Json 
records1=json.loads(records)
#refine the data according to get the desired results
records1=records1.replace("\\","")
records1=records1.replace(" ","")
#get the type of the data 
type(records1)
#Need to get it because to get the proper json for single ID
rec=records1[0:16665]
# need to do this because of the character wasn't follow the json rule
rec=rec.replace('"You"',"'//You//'")
#Now refine data load into the Json and create the key value pair 
d = json.loads(rec)
#get the value for payload
d['payload']

**Comment by vivek14632** [comment]
Is it working now? or still having issue?

**Comment by vivek14632** [comment]
```
fp=open('file.json')
datam=fp.readlines()
fp.close()

for line in datam:
     data=json.load(line)
     # now you can pull values

```

**Comment by mdedhe** [comment]
@vivek14632  I will try it and let you know the results

**Comment by mdedhe** [comment]
Instead of load function I used loads and it worked ...  thanks for the help @vivek14632 
```
import json
fp=open('/Users/mohitdedhe/Desktop/MohitsDocs/Certification and Projects/VProject/Files/2015-01-07-11.json')
datam=fp.readlines()
fp.close()

for line in datam:
    data=json.loads(line)
```
